# Generated by Django 4.0.4 on 2022-04-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
